# Generated by Django 4.2.5 on 2025-09-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteerprofile",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
