# Generated by Django 4.2.5 on 2025-09-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="donation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Pickup"),
                    ("ACCEPTED", "On its Way"),
                    ("COLLECTED", "Collected by Volunteer"),
                    ("DELIVERED", "Delivered"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("RESTAURANT", "Restaurant"),
                    ("NGO", "NGO"),
                    ("VOLUNTEER", "Volunteer"),
                ],
                default="ADMIN",
                max_length=10,
            ),
        ),
    ]
