# Generated by Django 4.2.5 on 2025-09-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_donation_accepted_at_alter_donation_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donationcamp",
            name="end_time",
        ),
        migrations.AddField(
            model_name="donationcamp",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="donation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Pickup"),
                    ("ACCEPTED", "On its Way"),
                    ("COLLECTED", "Collected by Volunteer"),
                    ("VERIFYING", "Pending Verification"),
                    ("DELIVERED", "Delivered & Verified"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
