# Generated by Django 4.2.5 on 2025-09-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_volunteerprofile_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="ngoprofile",
            name="banner_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="banner_images/ngos/"
            ),
        ),
        migrations.AddField(
            model_name="ngoprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/ngos/"
            ),
        ),
        migrations.AddField(
            model_name="restaurantprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/restaurants/"
            ),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/volunteers/"
            ),
        ),
    ]
