# Generated by Django 4.2.5 on 2025-09-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_ngoprofile_banner_image_ngoprofile_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Pickup"),
                    ("ACCEPTED", "On its Way"),
                    ("COLLECTED", "Collected by Volunteer"),
                    ("VERIFYING", "Pending Verification"),
                    ("DELIVERED", "Delivered & Verified"),
                ],
                db_index=True,
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
