# Generated by Django 4.2.5 on 2025-09-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_remove_donationcamp_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationcamp",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="donationcamp",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurantprofile",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurantprofile",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
