# Generated by Django 5.2.7 on 2025-10-05 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_alter_donation_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "icon_url",
                    models.CharField(
                        blank=True,
                        help_text="URL or emoji for badge icon",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="donation",
            name="rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1 Star"),
                    (2, "2 Stars"),
                    (3, "3 Stars"),
                    (4, "4 Stars"),
                    (5, "5 Stars"),
                ],
                help_text="Rating from 1 to 5 stars",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="review",
            field=models.TextField(
                blank=True,
                help_text="NGO's review of the volunteer delivery",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="webpush_subscription",
            field=models.TextField(
                blank=True, help_text="Web push subscription data (JSON)", null=True
            ),
        ),
        migrations.CreateModel(
            name="VolunteerBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_awarded", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.badge"
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to="portal.volunteerprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("volunteer", "badge")},
            },
        ),
    ]
