# Generated by Django 4.2.5 on 2025-09-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_donationcamp_latitude_donationcamp_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ngoprofile",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ngoprofile",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
